### ISSUE TITLE
Docker Compose error

### ISSUE THREAD

**Issue by calh** [pgEdge/nodectl#11]
Hi, I wanted to just try a quick demo with pgEdge to see how it behaves.  I found the docker compose setup, but it seems to want to install the spock extension way too early before the database starts up:

```
...
pgedge-n1_1  |   new: spock.conflict_resolution = 'last_update_wins'
pgedge-n1_1  |   new: spock.save_resolutions = 'on'
pgedge-n1_1  |   new: shared_preload_libraries = 'pg_stat_statements, spock'
pgedge-n1_1  | 
pgedge-n2_1  | pg16 stopping
pgedge-n1_1  | pg16 stopping
pgedge-n2_1  | pg16 starting on port 5432
pgedge-n1_1  | pg16 starting on port 5432
pgedge-n2_1  | 
pgedge-n2_1  | $ pg16/bin/psql -p 5432 -c "CREATE EXTENSION IF NOT EXISTS spock"  demo
pgedge-n2_1  | psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  the database system is starting up
pgedge-n1_1  | 
pgedge-n1_1  | $ pg16/bin/psql -p 5432 -c "CREATE EXTENSION IF NOT EXISTS spock"  demo
pgedge-n1_1  | psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  the database system is starting up
```

I've tried to trace through all of the python scripts that are used in the entrypoint, but it's really difficult with the remotely executed scripts.

**Comment by cmotyka** [comment]
Looking like an issue on this line:
https://github.com/pgEdge/nodectl/blob/main/cli/scripts/spock.py#L830

Right now it sleeps so that postgres has a chance to restart and then it begins running the psql commands to finish the install of the Spock extension. I'm going to work on a fix for this (checking that pg has started before continuing), and this will be coming out in the next release. 

In the meantime, the quick fix I can think of is putting a sed command in the to replace `time.sleep(3)` with `time.sleep(x)` in the file `hub/scripts/spock.py` in the file used by Docker: bootstrap.sh after line 39

**Comment by calh** [comment]
Another option that doesn't rely on the speed of the host, is a simple wait-loop to check if the server is up.  These are scattered around other Postgres image setups:

```
# After the post-init server is executed, wait for it to start up
# and be available for traffic
postinit_wait_for_startup() {
  export PGPASSWORD="${PGPASSWORD:-$POSTGRES_PASSWORD}"
  until psql -U $POSTGRES_USER -c '\q'; do
    >&2 echo "Waiting for to startup..."
    sleep 1
  done
  unset PGPASSWORD
}
```

**Comment by calh** [comment]
Oh, one more thing I noticed with the docker-compose.yml:  specifying `image` along with `build` will cause Docker Compose to _overwrite_ the image name.  In this case, it tags the pgedge image as literally `rockylinux:9` which then completely jacks anything else on your host that builds from `rockylinux:9`.  If you just remove the two lines specifying `image` it works fine.

**Comment by cmotyka** [comment]
Cool, that's similar to what I was going to do. The one thing is that the Docker images use curl to get the latest release so you can make that change in the pgEdge directory and then copy that file to the Docker images to replace the one that's downloaded to there in the curl command.

Will fix the second issue in the next release too, thanks!
